config/routes.rb
TaskApp::Application.routes.draw do

  resources :users do
    post 'create_task', :on => :collection

  end
    match '/users/destroy_task/:id', to: 'users#destory_task',as: "destroy_task_users",via: 'delete'

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
	  @user=User.new
	end

	def create
	  @user=User.new(name:params[:name],pwd:params[:pwd])
	  if @user.save
	  	flash[:success] = "添加新用户成功"
        redirect_to :action => :index, :id => @user
	  else
	  	flash[:success] = "添加新用户失败"
        redirect_to :back
	  end
	end

	def index
		@tasks=Task.where(user_id:params[:id])
	end

	def create_task
		@task=Task.new(content:params[:content],do_date:params[:do_date],user_id:params[:user_id])
		if @task.save
	  	  flash[:success] = "添加备忘成功"
          redirect_to :back
	    else
	  	  flash[:success] = "添加备忘失败"
          redirect_to :back
	    end
	end

	def destory_task
		@task=Task.find(params[:id])
		if @task.destroy
		  flash[:success] = "删除备忘成功"
          redirect_to :back
	    else
	  	  flash[:success] = "删除备忘失败"
          redirect_to :back
	    end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shade/_pop.html.erb
<div class="pop" id="pop_box">
  <div class="pop_title">
    <h3>短信内容</h3>
    <button type="button" class="pop_close_btn" aria-hidden="true">×</button>
  </div>
  <div class="pop-content">
  	<div class="time"><p></p></div>
  	<p class="own"></p>
  	<p class="message_content"></p>
  </div>
</div>

app/views/users/_task.html.erb
<tr>
  <td><%= task.created_at.strftime("%Y-%m-%d")%></td>
  <td><%= task.content%></td>
  <td><%= task.do_date.strftime("%Y-%m-%d") if task.do_date%></td>
  <td><%= link_to '完成', destroy_task_users_path(task), method: 'delete' %></td>
</tr>

app/views/users/index.html.erb
<h1>添加新备忘</h1>
<%= form_tag(create_task_users_path,method:'post') do %>
<label>内容</label>
<%= text_field_tag 'content',nil%>
<label>时间</label>
<%= text_field_tag 'do_date',nil%>
<%= hidden_field_tag :user_id,params[:id]%>
<%= submit_tag '添加'%>
<% end %>
<h2>我的任务</h2>
<table style="border:1px solid #000">
  <tr>
  	<th>创建时间</th>
  	<th>内容</th>
  	<th>执行时间</th>
  	<th>操作</th>
  </tr>
  <tbody>
    <%= render :partial => 'task',:collection =>@tasks%>
  </tbody>
</table>
<!-- test -->

app/views/users/new.html.erb
<h1>注册</h1>
<%= form_for(@user) do |f|%>
<label>姓名</label>
<%= f.text_field :name%>
<label>密码</label>
<%= f.password_field :pwd%>
<%= f.submit '保存'%>
<% end %>